web/router.ex
defmodule Schooldata.Router do
  use Schooldata.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Schooldata.CurrentUser
    plug Schooldata.CurrentRoles
  end

  scope "/", Schooldata do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    get "/user/:id",  RegistrationController, :profile
    
    resources "/registration",  RegistrationController
    get "/users/forgotpassword", RegistrationController, :forgotpassword
    post "/users/forgotpassword", RegistrationController, :forgotPasswordSave

    get "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/examinations", ExaminationController
    resources "/sections", SectionController
    resources "/profile",  ProfileController
    resources "/results",  ResultsController
    resources "/attendence",  AttendenceController
    resources "/homework",  HomeworkController
    resources "/complaints",  ComplaintsController
    resources "/payments",  PaymentsController
    get "/payment-types", PaymentDetailsController, :index
    post "/payment-types", PaymentDetailsController, :index
    get "/payments-list", PaymentDetailsController, :list
    post "/payments-list", PaymentDetailsController, :list
    
    post "/student/:class_id/id", AjaxController, :student_id_json
    post "/student/:student_id/name", AjaxController, :student_name_json
    

    resources "/admissions", AdmissionsController
#    get "/admissions/new", AdmissionsController, :new
#    post "/admissions", AdmissionsController, :create
    get "/admissions-import", AdmissionsController, :import
    post "/admissions-import", AdmissionsController, :import
    #get "/admissions", AdmissionsController, :list
  
  end

  # Other scopes may use custom stacks.
  # scope "/api", Schooldata do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Schooldata.LayoutView do
  use Schooldata.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
    <title>Schooldata!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
  </head>

  <body>

  <%= render "header.html", assigns %>
  <main role="main">
    <div class ="container">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  </div>
  <%= render @view_module, @view_template, assigns %>
  </main>

  
  <footer class="page-footer orange">
  <!--
    <div class="container">
       <div class="row">
           <div class="col s12">
             <h5 class="white-text">School Info</h5>
             <p class="grey-text text-lighten-4">Address: </p>
           </div>
        </div>
    </div>
    
     <div class="footer-copyright">
    -->
       <div class="container"> @Schooldata </div>
     <!-- </div> -->
  </footer>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/header.html.eex
<div class="navbar-fixed school-fixed-header">
  <nav class="school-navigation">
    <div class="nav-wrapper container">
      <ul class="right hide-on-med-and-down">
        <%= if @current_user do %>
         <li>Welcome  <%= @current_user.username %>!</li>
         <li><%= link "Sign out", to: session_path(@conn, :delete), method: "delete" %> </li>
        <% else %>
  	     <li><%= link "Register", to: registration_path(@conn, :new) %></li>
         <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
        <% end %>
      </ul>
    </div>
      
  </nav>
</div>

 <nav class="schooldata-navigation">
    <div class="nav-wrapper">
      <div class ="container">
      <a href="/" class="brand-logo">
        <image class="logo"src="<%= static_path(@conn, "/images/School_Logo.jpg") %>" /></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
         <%= if @current_user do %>
        <li><%= link "Profile", to: registration_path(@conn, :profile, @current_user) %></li>
        <li><%= link "Results", to: results_path(@conn, :index) %></li>
        <li><%= link "Attendence", to: attendence_path(@conn, :index) %></li>
        <li><%= link "Home Work", to: homework_path(@conn, :index) %></li>
        <li><%= link "Complaints Board", to: complaints_path(@conn, :index) %></li>
        <!-- <li><%= link "Payments", to: payments_path(@conn, :index) %></li> -->
        <li><a class="dropdown-button" href="<% payments_path(@conn, :index) %>" data-activates="dropdown1">Payments<i class="material-icons right">arrow_drop_down</i></a></li>
     
   <% end %>        
      </ul>
    </div>

<ul id="dropdown1" class="dropdown-content">
  <li><a href="<%= payments_path(@conn, :index) %>">Dashboard</a></li>
  <li class="divider"></li>
  <li><a href="#!">Transport</a></li>
  <li class="divider"></li>
  <li><a href="#!">Salaries</a></li>
  <li class="divider"></li>
  <li><a href="#!">Expenses</a></li>
</ul>

    </div>

  </nav>

web/templates/layout/pagination.html.eex
<%= if @assigns.total do %>

<%
  total = @assigns.total
  current_page = @assigns.current_page
  per_page = @assigns.per_page
  page_start_value = if total > 0, do: ((current_page - 1) * per_page) + 1, else: 0
  page_end_value = (current_page * per_page)
  page_end_value = if page_end_value < total, do: page_end_value, else: total
  total_pages = Decimal.new(Float.ceil(total/per_page))
  total_pages = Decimal.to_integer(total_pages)
%>

<!--
<span style="float:right;">Showing <%= page_start_value%> to <%= page_end_value %> of <%= total %> (<%= total_pages %> Pages)</span>
<br/>
-->
<input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>"/>
  <% last_page = if rem(@assigns.total, @assigns.per_page) == 0, do: div(@assigns.total, @assigns.per_page),
     else: div(@assigns.total, @assigns.per_page) + 1 %>
  <ul class="pager">
    <input type="hidden" name="current_page" id="current_page" value="<%= @assigns.current_page %>"/>
    <input type="hidden" name="pagination_action" id="pagination-action" value=""/>
    <%= if @assigns.current_page == 1 do %>
      <li id="first" class="previous disabled"><a href="<%= @assigns.url %>">&larr; First</a></li>
    <% else %>
      <li id="first" class="previous"><a href="<%= @assigns.url %>">&larr; First</a></li>
    <% end %>
    <% per_page_list = [10, 25, 50] %>
    <!-- <select id="per_page" name="per_page" class="form-control pagination-per-page">
      <%= for i <- per_page_list do %>
        <%= if @assigns.per_page == i do %>
          <option value="<%= i %>" selected><%= i %></option>
        <% else %>
          <option value="<%= i %>"><%= i %></option>
        <%= end %>
      <% end %>
    </select>
    -->
    <%= if @assigns.current_page == 1 do %>
      <li id="prev" class="disabled"><a href="<%= @assigns.url %>">&larr; Previous</a></li>
    <% else %>
      <li id="prev"><a href="<%= @assigns.url %>">&larr; Previous</a></li>
    <% end %>
    <%= if @assigns.current_page == last_page || @assigns.current_page < 0 do %>
      <li id="next" class="disabled"><a href="<%= @assigns.url %>">Next &rarr;</a></li>
    <% else %>
      <li id="next"><a href="<%= @assigns.url %>">Next &rarr;</a></li>
    <% end %>
    <%= if @assigns.current_page < 0 || @assigns.current_page == last_page do %>
      <li id="last" class="next disabled"><a href="<%= @assigns.url %>">Last &rarr;</a></li>
    <% else %>
      <li id="last" class="next"><a href="<%= @assigns.url %>">Last &rarr;</a></li>
    <% end %>
  </ul>
<% end %>