web/router.ex
defmodule Schooldata.Router do
  use Schooldata.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Schooldata.CurrentUser
    plug Schooldata.CurrentRoles
  end

  scope "/", Schooldata do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    get "/user/:id",  RegistrationController, :profile
    
    resources "/registration",  RegistrationController
    get "/users/forgotpassword", RegistrationController, :forgotpassword
    post "/users/forgotpassword", RegistrationController, :forgotPasswordSave

    get "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/examinations", ExaminationController
    resources "/sections", SectionController
    resources "/profile",  ProfileController
    resources "/results",  ResultsController
    resources "/attendence",  AttendenceController
    resources "/homework",  HomeworkController
    resources "/complaints",  ComplaintsController
    resources "/payments",  PaymentsController
    get "/payment-types", PaymentDetailsController, :index
    post "/payment-types", PaymentDetailsController, :index
    get "/payments-list", PaymentDetailsController, :list
    post "/payments-list", PaymentDetailsController, :list
    
    post "/student/:class_id/id", AjaxController, :student_id_json
    post "/student/:student_id/name", AjaxController, :student_name_json
    

    resources "/admissions", AdmissionsController
#    get "/admissions/new", AdmissionsController, :new
#    post "/admissions", AdmissionsController, :create
    get "/admissions-import", AdmissionsController, :import
    post "/admissions-import", AdmissionsController, :import
    #get "/admissions", AdmissionsController, :list
  
  end

  # Other scopes may use custom stacks.
  # scope "/api", Schooldata do
  #   pipe_through :api
  # end
end

lib/schooldata/helpers/payments_helper.ex
defmodule PaymentsHelper do
    alias Schooldata.Repo
    #import Plug.Conn
    import Ecto.Query 

    alias Schooldata.UserProfile
    alias Schooldata.Classes
    alias Schooldata.Payments
    alias Schooldata.UserPayments
    alias Schooldata.UserPaymentsDetails
  
    def load_payment_details(id) do
      payments = Repo.get(UserPayments, id)
      if payments == nil do
       {}
      end
      query = from(upd in UserPaymentsDetails, left_join: p in Payments, on: p.id == upd.payment_type_id,
      select: {p, upd}, where: [user_payments_id: ^id])
      payments_list = Repo.all(query)
      
      {payments, payments_list} 
    end

    def get_payment_types(_conn, _ \\ %{}) do
      {}
    end

    def get_payments_list(_conn, data \\ %{}) do
      query = from(upy in UserPayments, 
                   left_join: upyd in UserPaymentsDetails, on: upy.id == upyd.user_payments_id,
                   left_join: up in UserProfile, on: up.uid == upy.user_id, 
                   left_join: cs in Classes, on: up.class_id == cs.id,
                   left_join: p in Payments, on: p.id == upyd.payment_type_id,
                   select: {upy, upyd, up, cs, p},
                   where: upy.status == "closed"
                  )

      query = if data["class_id"] && data["class_id"] != "0" do
        from([upy, upyd, up, cs, p] in query, where: up.class_id == ^String.to_integer(data["class_id"]))
        else query
      end

      payments = Repo.all(query)    
      params = %{current_page: data["page"], total: 30, per_page: 10}
      {payments,  params}
    end

    def get_payment_totals(_conn, data \\ %{}) do

      # query = from(upyd in UserPaymentsDetails, 
      #              left_join: upy in UserPayments, on: upy.id == upyd.user_payments_id,
      #              left_join: up in UserProfile, on: up.uid == upy.user_id, 
      #              left_join: cs in Classes, on: up.class_id == cs.id,
      #              left_join: p in Payments, on: p.id == upyd.payment_type_id,
      #              where: upy.status == "closed",
      #              group_by: [upyd.payment_type_id, p.payment_name, up.class_id],
      #              order_by: p.payment_name,
      #              select: {sum(upyd.amount_paid), p.payment_name, up.class_id}
      #             )

      query = from(upyd in UserPaymentsDetails, 
                   left_join: upy in UserPayments, on: upy.id == upyd.user_payments_id,
                   left_join: up in UserProfile, on: up.uid == upy.user_id, 
                   left_join: cs in Classes, on: up.class_id == cs.id,
                   left_join: p in Payments, on: p.id == upyd.payment_type_id,
                   where: upy.status == "closed"
                  )


      query = if data["class_id"] && data["class_id"] != "0" do
         from([upyd, upy, up, cs, p] in query, 
           where: up.class_id == ^String.to_integer(data["class_id"]),
           group_by: [upyd.payment_type_id, p.payment_name, up.class_id],
           select: {sum(upyd.amount_paid), p.payment_name, up.class_id}
         )
      else 
        from([upyd, upy, up, cs, p] in query, 
           group_by: [upyd.payment_type_id, p.payment_name],
           select: {sum(upyd.amount_paid), p.payment_name, true}
         )
      end
      Repo.all(query)
    end
 
end

web/models/payments.ex
defmodule Schooldata.Payments do
    use Schooldata.Web, :model
    
    schema "payments" do
      field :payment_name, :string
    end    
end

web/controllers/payments_controller.ex
defmodule Schooldata.PaymentsController do
    use Schooldata.Web, :controller
    
    alias Schooldata.User
    alias Schooldata.UserPayments
    alias Schooldata.UserPaymentsDetails


    plug Schooldata.Plugs.RequireAuth when action in [:index, :new, :create]
   
    def index(conn, _params) do
     render conn, "payments.html"
    end

    def show(conn, params) do 
      {payments, payments_list} = PaymentsHelper.load_payment_details(params["id"])
      if payments == nil do
         render conn, "display_payment.html" , noresult: 1
      else
        user = Helper.load_user_details(payments.user_id)
        received = Helper.load_user_details(payments.received_id)
        total = Enum.reduce(payments_list, 0, fn({ _, payment}, acc) -> acc+Decimal.to_float(payment.amount_paid)  end) 
          |> Decimal.new
          |> Decimal.round(2)

        words = total |> Decimal.to_integer |> NumberToWord.say
        render conn, "display_payment.html" , user: user, payments: payments, list: payments_list, total: total, received: received, noresult: 2, words: words
      end
    end

    def new(conn, _params) do
      changeset = User.changeset(%User{}, %{})
      render conn, "add_payments.html" , changeset: changeset
    end   

    def create(conn, params) do
      {payments, payments_sel} = preapre_payments(conn.assigns.current_user.id, params)
       
      payments = Enum.filter(payments, fn {_, value} -> not(value in ["0", 0]) end) |> Map.new 
      payments = UserPayments.changeset(%UserPayments{}, payments)

      case Repo.insert(payments) do
        {:ok, payment} ->
        Enum.map(payments_sel, fn {type, amount} ->
          payments_list = UserPaymentsDetails.changeset(%UserPaymentsDetails{},
              %{"user_payments_id" => payment.id, 
                "payment_type_id" => type,
                "amount_paid" => String.to_integer(amount)
                })
            Repo.insert(payments_list)
          end)
        conn
            |> put_flash(:info, " Payment Successfully Done!")
            |> redirect(to: "/payments/#{payment.id}")
        {:error, changeset} ->
          conn
          |> put_flash(:info, "Unable to make payment. Try again with proper inputs")
          |> render("add_payments.html", changeset: changeset)
      end
    end   

    def preapre_payments(current_user, params) do     
      %{"amount" => amounts,  "comment" => comment,
          "user_id" => user,  "payment_id" => payments,
          "acadamic_year" => acadamic_year, "payment_mode" => payment_mode
      } = params

      amounts = Enum.filter(amounts, fn {_, value} ->  Integer.parse(value) != :error end) |> Map.new
      payments_sel = payments_selected(amounts, payments)
      total_amount = Enum.reduce(payments_sel, 0, fn({_, val}, acc) -> String.to_integer(val) + acc end)
      today_date = NaiveDateTime.utc_now
      
      all_payments = %{"payment_mode" => payment_mode, "user_id" => user,
                 "payment_date" => today_date,  "amount_paid" => total_amount,
                 "comment" => comment,  "received_id" => current_user,
                 "status" => "closed",  "inserted_at" => today_date,
                 "acadamic_year" => acadamic_year
      }
      {all_payments, payments_sel}
    end

    def payments_selected(amounts, payments) do
      Enum.reduce(payments, %{}, fn({key, val}, acc) ->
         if val != "0" and not(amounts[key] in ["", nil]) do
           Map.update(acc, String.to_integer(val), amounts[key], fn(prev_val) -> 
             Integer.to_string(String.to_integer("#{amounts[key]}") + String.to_integer("#{prev_val}"))     
           end)
         else 
           acc
         end       
       end)
    end
end

web/views/payments_view.ex
defmodule Schooldata.PaymentsView do
    use Schooldata.Web, :view

    def side_menu(conn, assigns, current_item) do
#       user = assigns[:current_user]
#       roles = assigns[:roles]
       side_menu = [view_all_payments: %{title: "Payments Dashboard", path: payments_path(conn, :index)}]
       side_menu = Keyword.put_new(side_menu, :payment_types, %{title: "Fee Structure", path: payment_details_path(conn, :index)}) 
       side_menu = Keyword.put_new(side_menu, :payment_list, %{title: "Payments List", path: payment_details_path(conn, :list)}) 
       side_menu = Keyword.put_new(side_menu, :add_payments, %{title: "Add New Payment", path: payments_path(conn, :new)}) 

       {_, side_menu} = Keyword.get_and_update(side_menu, current_item, fn cv -> {cv, Map.put(cv, :active, "active")} end)
        
       Enum.reverse side_menu

    end
end

web/templates/payments/add_payments.html.eex
<br/><br/>
<div class="row">

<div class="col s2">
    <ul class="collection">
          <%  menu_items = side_menu(@conn, assigns, :add_payments)   %>
          <%= for { _ , item} <- menu_items do %>
            <li class = "collection-item <%= item[:active] %>"><a href="<%= item.path %>"><%= item.title %></a> </li>
          <% end %>
    </ul>
  </div>

  <div class="col s10">
   <h5>Add New Payment</h5>
 
   
  <%= form_for @changeset, payments_path(@conn, :create), [class: "add-payments-form"], fn f -> %>
   <div class="row">
   <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
  <% end %>
      <div class = 'row'>
        <div class="col s5">
           <label for="name">Academic Year</label>
            <select name="acadamic_year" class="form-control">
               <option value="0">---Select---</option>
               <option value="2017-18" selected>2017-18</option>
               <option value="2018-19">2018-19</option>
               <option value="2019-20">2019-20</option>
            </select>
        </div>
      </div>

       <div class = 'row'>
           <div class="col s4">
             <label for="name">Class</label>
             <% classes = Helper.get_classes %>
             <select name="class_id" class="form-control">
                      <option value="0">---Select Class---</option>
                       <%= for class <- classes do %> 
                              <option value="<%= class.id %>" ><%= class.name %></option>
                       <% end %>
              </select>
          </div>

          <div class="col s4">
             <label for="name">Student ID</label>
             <select name="user_id" class="form-control student_id">
                <option value="0">---Select Class---</option>
             </select>
          </div>

          <div class="col s4">
             <label for="name">Student Name</label>
             <select name="full_name" class="form-control student_name">
                <option value="0">---Select Class---</option>
             </select>
          </div>


        </div>
  
        <% payments = Helper.get_payment_types %>
       <div class = 'row card' >
             <table class = "payment-types">
               <thead>
                 <tr><th>Fee Type</th><th>Amount</th><th>Actions</th></tr>
               </thead>
               <tbody>
                 <tr>
                   <td>
                       <select name="payment_id[1]" class="form-control payment-type">
                         <option value="0">---Select Class---</option>
                          <%= for payment <- payments do %> 
                              <option value="<%= payment.id %>" ><%= payment.payment_name %></option>
                          <% end %>
                       </select>
                   </td>
                     
                   <td>
                     <input type="text" class="amount" name="amount[1]" placeholder="Amount" value='' />
                    </td>

                   <td >
                     <a class="hidden delete-row"><i class="material-icons">delete</i></a>
                    </td>

                 </tr>
               </tbody>
             </table>

           <button class="row col s2  payment_add_more btn btn-small">Add more</button>
      
        </div>


        <div class = 'row'>
           <div class="col s5">
              <label>Payment Mode</label>
               <select name="payment_mode" class="form-control">
                  <option value="0">-- Payment Mode --</option>
                  <option value="cash">Cash</option>
                  <option value="card">Card</option>
                  <option value="check">Check</option>
               </select>
           </div>
        </div>


        <div class = 'row'>
           <div class="col s5">
              <label>Comments</label>
              <input type="text" class="comment" name="comment" placeholder="Comment / Check or Card Number" value='' />
           </div>
        </div>

     

        <div class="row">  
          <div class="col s6">
             <%= submit "Save", class: "btn btn-primary" %>
           </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

web/templates/payments/display_payment.html.eex
<div class="row">
  <div class="col s2">
    <ul class="collection">
          <%  menu_items = side_menu(@conn, assigns, :view_all_payments)   %>
          <%= for { _ , item} <- menu_items do %>
            <li class = "collection-item <%= item[:active] %>"><a href="<%= item.path %>"><%= item.title %></a> </li>
          <% end %>
    </ul>
  </div>

<%= if @noresult == 1 do %>
  <br/><br/>
  <div class="col s7 center"><h4>No Bill Found.</h4></div>
<% else %>
  <div class="col s7  card">
        <div class="row center"><h5>Acadamic Year : <%= @payments.acadamic_year %> </h5></div>      
        <div class="row user-info">
           <div class="col s6"> 
              <p class="bill-info"><b>Name : </b><%= @user.full_name %></p>   
              <p class="bill-info"><b>Roll Number : </b><%= @user.roll_number %></p>   
              <p class="bill-info"><b>Class : </b><%= @user.class_id %></p>
              <p class="bill-info"><b>Section : </b><%= @user.section_id %></p>
            </div>

          <div class="col s6">
            <div class="right-content"><b>Bill No : </b> RECPT-<%= @payments.acadamic_year %>-<%= @payments.id %></div>
            <div class="right-content"><b>Bill Date : </b><%= @payments.payment_date.year %>-<%= @payments.payment_date.month %>-<%= @payments.payment_date.day %></div>
          </div>   
        </div>
        
        <div class="row">
         <div class="col s12">

          <div class="title center"><h5>Payment Details</h5></div>   
            <div class="bill-item">
              <div class="bill-type"><b>Particulars</b></div>   
              <div class="right-content"><b>Paid Amount</b></div>   
            </div>

            <%= for {payment, pay_l} <- @list do %>   
            <div class="bill-item">
              <div class="bill-type"><strong><%= payment.payment_name %></strong></div>   
              <div class="right-content"><%= pay_l.amount_paid |> Decimal.new |> Decimal.round(2) %></div>   
            </div>
           <% end %>
             <div class="bill-item ">
               <div class="bill-type"><b>Total Paid</b></div>   
               <div class="right-content"><b><%= @total %></b></div>   
             </div>
             <br/>
             <div class ="capitalize"><b>In words : </b>Rs. <%=  @words  %> only/-</div>

            </div>
          </div>

          <div class="row">
            <div class="title center"><h5>Payment Mode</h5></div>   
              <div class="col s8">
                <p class="bill-info"><b>Mode : </b><%= @payments.payment_mode %></p>   
                <p class="bill-info"><b>Details:</b> <%= @payments.comment %></p>  
              </div>

              <div class="col s4 right-content">
                <p class="bill-info"><b>Received By</b></p>   
                <p class="bill-info"><%= @received.full_name %></p>  
              </div>
          </div>

    <div class="row col s8">
       NOTE:
    </div>

  </div>
<% end %>

</div>

web/templates/payments/payments.html.eex
<ul class = "collapsible" data-collapsible = "accordion">
         <li>
            <div class = "collapsible-header active">
               <i class = "material-icons">dashboard</i><b>Dashboard Widgets</b></div>
            <div class = "collapsible-body">
            
            <div class="row">
<!--  <div class="col s2">
    <ul class="collection">
          <%  menu_items = side_menu(@conn, assigns, :view_all_payments)   %>
          <%= for { _ , item} <- menu_items do %>
            <li class = "collection-item <%= item[:active] %>"><a href="<%= item.path %>"><%= item.title %></a> </li>
          <% end %>
    </ul>
  </div>
-->
      
  <div class="row dashboard-items">
     <div class="row center">
          <div class="col s2 collection red"><a href="<%= payments_path(@conn, :new) %>">Add New Payment</a></div>
          <div class="col s2 collection blue" ><a href="<%= payment_details_path(@conn, :index) %>">Fee Structure</a></div>
          <div class="col s2 collection green"><a href="<%= payment_details_path(@conn, :list) %>">Payments List</a></div>
          <div class="col s2 collection alloy">Transport</div>
          <div class="col s2 collection cyellow">Salaries</div>
          <div class="col s2 collection bitter">Others</div>
     </div>

     <div class="row center">
          <div class="col s2 collection ceil"><a href="<%= admissions_path(@conn, :index) %>">Admissions</a></div>
          <div class="col s2 collection sgreen">Student Profiles</div>
          <div class="col s2 collection ered">Exams/Results</div>
          <div class="col s2 collection fdrab">Attendence/Holidays</div>
          <div class="col s2 collection fed">Bus Routes</div>
          <div class="col s2 collection desire">Complaints</div>
     </div>
      <div class="row center">
          <div class="col s2 collection bgreen">Staff</div>
          <div class="col s2 collection cgrey">Work Sheets</div>
          <div class="col s2 collection caramel">Leaves</div>
          
     </div>
  </div>
</div>

            
            </div>
         </li>
        </ul>

<br/>


<div class="row">
  <div class="col s6">
      <div class="row">
        <div class="col s12">              
               <script src="https://code.highcharts.com/highcharts.js"></script>
               <script src="https://code.highcharts.com/modules/exporting.js"></script>
               <div id="container" style=" height: 400px; margin: 0 auto"></div>
               
               <script>
                  Highcharts.chart('container', {
                     chart: {type: 'column'},
                     title: {text: 'Overall Payments'},
                     xAxis: {categories: ['10th', '9th', '8th', '7th', '6th','5th', '4th', '3rd', '2nd', '1st']},
                     yAxis: { min: 0,
                              title: {text: 'Total Payments of the year 2017-18'},
                              stackLabels: {
                                enabled: true,
                                style: {
                                  fontWeight: 'bold',
                                  color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                                }
                              }
                            },
                      legend: { align: 'right',x: -30,verticalAlign: 'top',y: 25,floating: true,
                                backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                borderColor: '#CCC',borderWidth: 1,shadow: false
                              },
                      tooltip: {
                                 headerFormat: '<b>{point.x}</b><br/>',
                                 pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
                                },
                      plotOptions: {
                      column: {
                               stacking: 'normal',
                               dataLabels: {enabled: true,color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'}
                      }
                    },
                    series: [{name: 'Pending',data: [100000, 90000, 80000, 70000, 60000, 50000, 40000, 30000,20000, 10000]}, 
                             {name: 'Received',data: [20000, 20000, 20000, 20000, 20000,20000,20000,20000,20000,20000]}
                             ]
                 });
                </script>
              
      </div>
    </div>
  </div>

  <div class="col s5">
      <div class="row">
        <div class="col s12">      
               <div id="container2" style="height: 400px; margin: 0 auto"></div>
               
               <script>
                  Highcharts.chart('container2', {
                     chart: {type: 'column'},
                     title: {text: 'Transport Payments'},
                     xAxis: {categories: ['10th', '9th', '8th', '7th', '6th','5th', '4th', '3rd', '2nd', '1st']},
                     yAxis: { min: 0,
                              title: {text: 'Total Payments of the year 2017-18'},
                              stackLabels: {
                                enabled: true,
                                style: {
                                  fontWeight: 'bold',
                                  color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                                }
                              }
                            },
                      legend: { align: 'right',x: -30,verticalAlign: 'top',y: 25,floating: true,
                                backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                borderColor: '#CCC',borderWidth: 1,shadow: false
                              },
                      tooltip: {
                                 headerFormat: '<b>{point.x}</b><br/>',
                                 pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
                                },
                      plotOptions: {
                      column: {
                               stacking: 'normal',
                               dataLabels: {enabled: true,color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'}
                      }
                    },
                    series: [{name: 'Pending',data: [100000, 90000, 80000, 70000, 60000, 50000, 40000, 30000,20000, 10000]}, 
                             {name: 'Received',data: [20000, 20000, 20000, 20000, 20000,20000,20000,20000,20000,20000]}
                             ]
                 });
                </script>
              
      </div>
    </div>
  </div>
</div>