web/router.ex
defmodule Schooldata.Router do
  use Schooldata.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Schooldata.CurrentUser
    plug Schooldata.CurrentRoles
  end

  scope "/", Schooldata do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    get "/user/:id",  RegistrationController, :profile
    
    resources "/registration",  RegistrationController
    get "/users/forgotpassword", RegistrationController, :forgotpassword
    post "/users/forgotpassword", RegistrationController, :forgotPasswordSave

    get "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/examinations", ExaminationController
    resources "/sections", SectionController
    resources "/profile",  ProfileController
    resources "/results",  ResultsController
    resources "/attendence",  AttendenceController
    resources "/homework",  HomeworkController
    resources "/complaints",  ComplaintsController
    resources "/payments",  PaymentsController
    get "/payment-types", PaymentDetailsController, :index
    post "/payment-types", PaymentDetailsController, :index
    get "/payments-list", PaymentDetailsController, :list
    post "/payments-list", PaymentDetailsController, :list
    
    post "/student/:class_id/id", AjaxController, :student_id_json
    post "/student/:student_id/name", AjaxController, :student_name_json
    

    resources "/admissions", AdmissionsController
#    get "/admissions/new", AdmissionsController, :new
#    post "/admissions", AdmissionsController, :create
    get "/admissions-import", AdmissionsController, :import
    post "/admissions-import", AdmissionsController, :import
    #get "/admissions", AdmissionsController, :list
  
  end

  # Other scopes may use custom stacks.
  # scope "/api", Schooldata do
  #   pipe_through :api
  # end
end

web/controllers/profile_controller.ex
defmodule Schooldata.ProfileController do
    use Schooldata.Web, :controller
    
    alias Schooldata.UserProfile
    alias Schooldata.User

    def edit(conn, %{"id" => user_id}) do
        class_list = Enum.reduce(Helper.get_classes(), [], fn(f, acc) -> 
            [{ f.name, f.id}| acc]
        end) |> Enum.reverse
    
        section_list = Enum.reduce(Helper.get_sections(), [], fn(f, acc) -> 
            [{ f.name, f.id}| acc]
        end) |> Enum.reverse
    
        
        user = Repo.get_by(UserProfile,[uid: user_id ])
        changeset = UserProfile.changeset(user)

        class_sections = %{classes: class_list, sections: section_list}
        render conn, "edit.html", changeset: changeset, user: user, class_sections: class_sections
    end
    
    def update(conn, %{"id" => id, "user_profile" => user_profile}) do
        old_profile = Repo.get(UserProfile, id)
        %{"joining_date" => joining_date, 
          "date_of_birth" => date_of_birth,
          "mobile" => mobile,
          "class_id" => class_id,
          "section_id" => section_id} = user_profile
        { _ , joindate } = NaiveDateTime.new(String.to_integer(joining_date["year"]),
          String.to_integer(joining_date["month"]),
          String.to_integer(joining_date["day"]), 0 ,0, 0)

        { _ , dob } = NaiveDateTime.new(String.to_integer(date_of_birth["year"]),
          String.to_integer(date_of_birth["month"]),
          String.to_integer(date_of_birth["day"]), 0 ,0, 0)

        user_profile = Map.put(user_profile, "joining_date", joindate)
        user_profile = Map.put(user_profile, "date_of_birth", dob)
        user_profile = Map.put(user_profile, "mobile", String.to_integer(mobile))
        
        user_profile = Map.put(user_profile, "class_id", String.to_integer(class_id))
        user_profile = Map.put(user_profile, "section_id", String.to_integer(section_id))



        #  IO.puts "++++++++++++"
        #  IO.inspect(user_profile)
        #  IO.puts "++++++++++++++"

        changeset = UserProfile.changeset(old_profile, user_profile)
        user = Repo.get!(User, conn.assigns.current_user.id)

        class_list = Enum.reduce(Helper.get_classes(), [], fn(f, acc) -> 
            [{ f.name, f.id}| acc]
        end) |> Enum.reverse
    
        section_list = Enum.reduce(Helper.get_sections(), [], fn(f, acc) -> 
            [{ f.name, f.id}| acc]
        end) |> Enum.reverse

        class_sections = %{classes: class_list, sections: section_list}
        

        case Repo.update(changeset) do
            {:ok, _profile} ->
                    conn
                    |> put_flash(:info, "Profile Updated")
                    |> redirect(to: registration_path(conn, :profile, user))
                {:error, changeset} ->
                    render conn, "edit.html", changeset: changeset, user: user, class_sections: class_sections
            end

    end
    
end

web/views/profile_view.ex
defmodule Schooldata.ProfileView do
    use Schooldata.Web, :view
  end

web/templates/profile/edit.html.eex
<div class="container">
  <div class="row center card ">
 
  <h4>Update  <%= @current_user.username %> Profile</h4>
   
  <%= form_for @changeset, profile_path(@conn, :update, @user), [multipart: true], fn f -> %>
   <div class="row">
   <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
  <% end %>
      <div class="input-field col s6 offset-s3">
         <label>Full Name</label>
         <%= text_input f, :full_name, placeholder: "Full Name", class: "form-control, validate", id: "icon_prefix" %>
         <%= error_tag f, :full_name %>
      </div>
      <div class="input-field col s6 offset-s3">
         <label>Roll Number</label>
           <%= text_input f, :roll_number, placeholder: "Role Name", class: "form-control, validate" %>
           <%= error_tag f, :roll_number %>
      </div>
      
       <div class="input-field col s6 offset-s3">
          <label>Father Name</label>
           <%= text_input f, :father_name, placeholder: "Father Name", class: "form-control, validate" %>
           <%= error_tag f, :father_name %>
      </div>

      <div class="input-field col s6 offset-s3">
           <label>Mother Name</label>
           <%= text_input f, :mother_name, placeholder: "Mother Name", class: "form-control, validate" %>
           <%= error_tag f, :mother_name %>
      </div>

      <div class="input-field col s6 offset-s3">
           <label>Parents Mobile Number</label>
           <%= text_input f, :mobile, placeholder: "Mobile Number", class: "form-control, validate" %>
           <%= error_tag f, :mobile %>
      </div>
      <div class="input-field col s6 offset-s3">
          <label>Date Of Birth</label>
            <%= date_select f, :date_of_birth, builder: fn b -> %>
             <%= b.(:day, []) %>
             <%= b.(:month, []) %>
             <%= b.(:year, [options: 1980..2025]) %>
          <% end %>
           <%= error_tag f, :date_of_birth %>
      </div>
      <div class="input-field col s6 offset-s3">
          <label>Joining Date</label>
            <%= date_select f, :joining_date, builder: fn b -> %>
             <%= b.(:day, []) %>
             <%= b.(:month, []) %>
             <%= b.(:year, [options: 1980..2025]) %>
          <% end %>
           <%= error_tag f, :joining_date %>
      </div>
      <div class="row">&nbsp;</div>
      <div class="input-field col s6 offset-s3">
          <label>class</label>         
          <%= select f, :class_id, @class_sections[:classes], class: "form-control" %>
          <%= error_tag f, :class_id %>
      </div>
      <div class="input-field col s6 offset-s3">
          <label>Section</label>         
          <%= select f, :section_id, @class_sections[:sections], class: "form-control" %>
          <%= error_tag f, :section_id %>
      </div>

      <div class="input-field col s6 offset-s3">
          <label>Upload Photo</label>
           <%= file_input f, :photo, class: "form-control" %>
        </div>

        <div class="container row">  
          <div class="input-field col s6 offset-s6">
             <%= submit "Save", class: "btn btn-primary" %>
           </div>
        </div>
      </div>
    <% end %>
  </div>
</div>