web/router.ex
defmodule Schooldata.Router do
  use Schooldata.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Schooldata.CurrentUser
    plug Schooldata.CurrentRoles
  end

  scope "/", Schooldata do
    pipe_through [:browser, :with_session] # Use the default browser stack

    get "/", PageController, :index
    get "/user/:id",  RegistrationController, :profile
    
    resources "/registration",  RegistrationController
    get "/users/forgotpassword", RegistrationController, :forgotpassword
    post "/users/forgotpassword", RegistrationController, :forgotPasswordSave

    get "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/examinations", ExaminationController
    resources "/sections", SectionController
    resources "/profile",  ProfileController
    resources "/results",  ResultsController
    resources "/attendence",  AttendenceController
    resources "/homework",  HomeworkController
    resources "/complaints",  ComplaintsController
    resources "/payments",  PaymentsController
    get "/payment-types", PaymentDetailsController, :index
    post "/payment-types", PaymentDetailsController, :index
    get "/payments-list", PaymentDetailsController, :list
    post "/payments-list", PaymentDetailsController, :list
    
    post "/student/:class_id/id", AjaxController, :student_id_json
    post "/student/:student_id/name", AjaxController, :student_name_json
    

    resources "/admissions", AdmissionsController
#    get "/admissions/new", AdmissionsController, :new
#    post "/admissions", AdmissionsController, :create
    get "/admissions-import", AdmissionsController, :import
    post "/admissions-import", AdmissionsController, :import
    #get "/admissions", AdmissionsController, :list
  
  end

  # Other scopes may use custom stacks.
  # scope "/api", Schooldata do
  #   pipe_through :api
  # end
end

web/models/sections.ex
defmodule Schooldata.Section do
    use Schooldata.Web, :model
    
    use Ecto.Schema
    import Ecto.Changeset

    schema "sections" do
      field :name, :string
      has_one :user_profile, Schooldata.UserProfile
    end


    def changeset(struct, params \\ %{}) do
      struct
      |> cast(params, [:name])
      |> validate_required([:name])
    end
end

web/controllers/section_controller.ex
defmodule Schooldata.SectionController do
  @moduledoc false

  use Schooldata.Web, :controller
  alias Schooldata.Section


  def index(conn, _) do


    sections = Repo.all(Section)

    conn
    |> render("index.html", sections: sections)
  end

  def new(conn, _) do
    section = Section.changeset(%Section{}, %{})
    render conn, "form.html", section: section
  end

  def create(conn, %{"section" => section}) do
    section = Section.changeset(%Section{}, section)

    case Repo.insert(section) do
      {:ok, _} ->
        conn
        |> put_flash(:success, "Section saved")
        |> redirect(to: "/sections")
      {:error, sec} ->
        conn
        |> put_flash(:error, "Section not saved")
        |> render("form.html", section: sec)
    end
  end

end

web/views/section_view.ex
defmodule Schooldata.SectionView do
  @moduledoc false

  use Schooldata.Web, :view

end

web/templates/section/form.html.eex
<div class="container">
  <div class="row center card ">

  <h4>Sections</h4>

  <%= form_for @section, section_path(@conn, :create), fn f -> %>
   <div class="row">
   <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
  <% end %>
      <div class="input-field col s6 offset-s3">
         <label>Section Name</label>
         <%= text_input f, :name, placeholder: "Name", class: "form-control, validate", id: "icon_prefix" %>
         <%= error_tag f, :name %>
      </div>

      <div class="container row">
                    <div class="input-field col s6 offset-s6">
                      <%= submit "Save", class: "btn btn-primary" %>
                    </div>
              </div>

    <% end %>
  </div>
  </div>
</div>

web/templates/section/index.html.eex
<div class="container">
  <div class="row center card ">

  <h4>Sections</h4>
  <div class="col s3">
<%= render Schooldata.SharedView, "sidebar.html" %>
        </div>
        <div class="col s6">
<table class="striped">
            <thead>
              <tr>
                  <th>Name</th>
              </tr>
            </thead>
            <tbody>
              <%=  for section <- @sections do %>

                  <tr>
                      <td><%= section.name %></td>

                  </tr>
            <% end %>

            
            </tbody>
          </table>
          </div>
          </div>
          </div>